### ISSUE TITLE
Bing

### ISSUE THREAD

**Issue by Ian-Drunkenson** [Zaczero/pihole-phishtank#2]
wouldn block whole Bing (www.bing.com) einther, even if you dont like Mircosoft.

**Comment by Zaczero** [comment]
The bing was blocked on PhishTank with this rule:
https://phishtank.org/phish_detail.php?phish_id=8016364

I have added a new pattern to skip cuch cases:
```sh
    # skip if url contains www in path or query or fragment
    if [[ $url =~ ^https?:\/\/.*?\/.*[Ww]{3} ]]; then
        continue
    fi
```

This project is a zero-maintenance blocklist, meaning I do not personally manage the whitelists/blacklists. The hosts list is generated algorithmically. "even if you dont like Mircosoft" - bugs like these have nothing to do with my personal preferences :+1:.
